name: Build & Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          version: 12
      - run: npm ci
      - run: npm run build
      - run: npm test

  build-docker:
    needs: [build-and-test]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - run: docker build .
